name: Preview Deploy
on:
  pull_request:
    branches: master
jobs:
    sdtt:
      runs-on: ubuntu-latest
      name: Run Structured Data Tests
      steps:
          - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
              node-version: 12.x
          - name: Run Structured Data Test
            run: |
                 npm i structured-data-testing-tool -g
                 sdtt --url  dtt --url https://liberty-portal.netlify.app/how-to-make-a-face-framing-lace-braid-at-home  --schemas "jsonld:Article"  -p Twitter -p Facebook --presets SocialMedia -i            
          
