name: Preview Deploy
on:
  pull_request:
    branches: master
jobs:
   
    lighthouse_check:
      runs-on: ubuntu-latest
      name: Run Lighthouse Checks
      needs: [deploy_preview]
      steps:
          - name: Checkout code
            uses: actions/checkout@v1 
          - name: Audit URLs using Lighthouse
            uses: treosh/lighthouse-ci-action@v3
            with:
              urls: |
                ${{ needs.deploy_preview.outputs.url }}
                ${{ needs.deploy_preview.outputs.url }}/how-to-do-a-dutch-braid-in-six-easy-steps
              uploadArtifacts: true # save results as an action artifacts
              temporaryPublicStorage: true # upload lighthouse report to the temporary storage
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
    sdtt:
      runs-on: ubuntu-latest
      name: Run Structured Data Tests
      needs: [deploy_preview]
      steps:
          - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
              node-version: 12.x
          - name: Run Structured Data Test
            run: |
                 npm i structured-data-testing-tool -g
                 sdtt --url  ${{ needs.deploy_preview.outputs.url }}               
          
    Cypress:
      runs-on: ubuntu-latest
      name: Run e2e Cypress Tests
      needs: [deploy_preview]
      steps:
          - name: Checkout code
            uses: actions/checkout@v1
          - name: Use Node.js 12.x
            uses: actions/setup-node@v1
            with:
              node-version: 12.x
          - name: Cypress Run
            uses: cypress-io/github-action@v1
            env:
             CYPRESS_baseUrl:  ${{ needs.deploy_preview.outputs.url }}